import {BridgeKit} from '@circle-fin/bridge-kit';
import {createViemAdapterFromProvider} from '@circle-fin/adapter-viem-v2';
import {state,emit,task,refreshWallet} from './chain.js';
export const bridgeState={result:null,steps:[],estimate:null,account:null};
const recoveryKey='arrey-circle-recovery-v1';
try{const saved=JSON.parse(localStorage.getItem(recoveryKey)||sessionStorage.getItem(recoveryKey)||'null');if(saved?.result?.destination?.chain?.chain==='Arc_Testnet'&&['Ethereum_Sepolia','Base_Sepolia'].includes(saved.result.source?.chain?.chain)){Object.assign(bridgeState,saved);}}catch{}
function remember(){try{const value=JSON.stringify({result:bridgeState.result,steps:bridgeState.steps,account:bridgeState.account},(_,v)=>typeof v==='bigint'?v.toString():v);localStorage.setItem(recoveryKey,value);sessionStorage.setItem(recoveryKey,value);}catch{}}
function clearRecovery(){try{localStorage.removeItem(recoveryKey);sessionStorage.removeItem(recoveryKey);}catch{}}
const kit=new BridgeKit();
kit.on('*',event=>{const v=event.values;if(v?.name){const next={name:String(v.name),state:String(v.state||'pending'),txHash:v.txHash||v.data?.txHash||null};const i=bridgeState.steps.findIndex(s=>s.name===next.name);if(i>=0)bridgeState.steps[i]=next;else bridgeState.steps.push(next);state.step=`Circle CCTP · ${next.name}: ${next.state}`;remember();emit();}});
async function adapter(){if(!state.provider||!state.account)throw Error('Connect your wallet first.');return createViemAdapterFromProvider({provider:state.provider});}
function params(a,chain,amount){if(!['Ethereum_Sepolia','Base_Sepolia'].includes(chain))throw Error('Only Sepolia testnets can bridge into this app.');return {from:{adapter:a,chain},to:{adapter:a,chain:'Arc_Testnet'},amount,token:'USDC'};}
export async function estimateBridge(chain,amount){const a=await adapter();bridgeState.estimate=await kit.estimate(params(a,chain,amount));return bridgeState.estimate;}
export async function bridge(chain,amount){return task(async()=>{if(bridgeState.result&&bridgeState.result.state!=='success')throw Error('Resume the existing bridge before starting another.');const a=await adapter();bridgeState.account=state.account;bridgeState.steps=[];bridgeState.result=null;remember();state.step='Approve the Circle bridge steps in your wallet';emit();bridgeState.result=await kit.bridge(params(a,chain,amount));remember();if(bridgeState.result.state!=='success')throw Error('Bridge not complete. Use Resume bridge; do not start another transfer.');await refreshWallet();clearRecovery();return bridgeState.result;});}
export async function retryBridge(){return task(async()=>{if(!bridgeState.result||bridgeState.result.state==='success')throw Error('No incomplete bridge to resume.');if(bridgeState.account!==state.account)throw Error('Reconnect the wallet that started this bridge.');const a=await adapter();bridgeState.result=await kit.retry(bridgeState.result,{from:a,to:a});remember();if(bridgeState.result.state!=='success')throw Error('Bridge still pending. Check the recorded transaction on the source explorer.');await refreshWallet();clearRecovery();return bridgeState.result;});}
